version: '3'
services:
    app:
        container_name: docker-student-details
        restart: always
        build: .
        ports:
            - '8080:5000'
        links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - '27017:27017'